level2_mapping = [ #85
                    ['001.Black_footed_Albatross', '002.Laysan_Albatross', '003.Sooty_Albatross'],
                    ['004.Groove_billed_Ani'],
                    ['005.Crested_Auklet', '006.Least_Auklet', '007.Parakeet_Auklet'],
                    ['008.Rhinoceros_Auklet', '106.Horned_Puffin'],
                    ['009.Brewer_Blackbird', '011.Rusty_Blackbird', '049.Boat_tailed_Grackle'],
                    ['010.Red_winged_Blackbird', '026.Bronzed_Cowbird', '027.Shiny_Cowbird'],
                    ['012.Yellow_headed_Blackbird', '013.Bobolink'],
                    ['014.Indigo_Bunting'],
                    ['015.Lazuli_Bunting', '016.Painted_Bunting', '054.Blue_Grosbeak'],
                    ['017.Cardinal'],
                    ['018.Spotted_Catbird'],
                    ['019.Gray_Catbird'],
                    ['020.Yellow_breasted_Chat'],
                    ['021.Eastern_Towhee', '148.Green_tailed_Towhee'],
                    ['023.Brandt_Cormorant', '024.Red_faced_Cormorant', '025.Pelagic_Cormorant'],
                    ['028.Brown_Creeper'],
                    ['029.American_Crow', '030.Fish_Crow', '107.Common_Raven', '108.White_necked_Raven'],
                    ['031.Black_billed_Cuckoo', '033.Yellow_billed_Cuckoo'],
                    ['032.Mangrove_Cuckoo'],
                    ['034.Gray_crowned_Rosy_Finch', '035.Purple_Finch'],
                    ['036.Northern_Flicker', '188.Pileated_Woodpecker'],
                    ['037.Acadian_Flycatcher'],
                    ['038.Great_Crested_Flycatcher', '041.Scissor_tailed_Flycatcher', '077.Tropical_Kingbird', '078.Gray_Kingbird'],
                    ['039.Least_Flycatcher', '043.Yellow_bellied_Flycatcher'],
                    ['040.Olive_sided_Flycatcher', '102.Western_Wood_Pewee'],
                    ['042.Vermilion_Flycatcher'],
                    ['045.Northern_Fulmar'],
                    ['046.Gadwall', '087.Mallard', '089.Hooded_Merganser', '090.Red_breasted_Merganser'],
                    ['047.American_Goldfinch', '048.European_Goldfinch'],
                    ['050.Eared_Grebe', '051.Horned_Grebe'],
                    ['052.Pied_billed_Grebe'],
                    ['053.Western_Grebe'],
                    ['055.Evening_Grosbeak'],
                    ['056.Pine_Grosbeak'],
                    ['057.Rose_breasted_Grosbeak'],
                    ['058.Pigeon_Guillemot'],
                    ['059.California_Gull', '060.Glaucous_winged_Gull', '061.Heermann_Gull', '062.Herring_Gull', '063.Ivory_Gull', '064.Ring_billed_Gull', '065.Slaty_backed_Gull', '066.Western_Gull', '084.Red_legged_Kittiwake'],
                    ['067.Anna_Hummingbird', '068.Ruby_throated_Hummingbird', '069.Rufous_Hummingbird', '070.Green_Violetear'],
                    ['071.Long_tailed_Jaeger', '072.Pomarine_Jaeger'],
                    ['073.Blue_Jay', '074.Florida_Jay'],
                    ['076.Dark_eyed_Junco', '122.Harris_Sparrow', '132.White_crowned_Sparrow', '133.White_throated_Sparrow'],
                    ['079.Belted_Kingfisher', '082.Ringed_Kingfisher'],
                    ['080.Green_Kingfisher', '081.Pied_Kingfisher'],
                    ['083.White_breasted_Kingfisher'],
                    ['085.Horned_Lark'],
                    ['086.Pacific_Loon'],
                    ['088.Western_Meadowlark'],
                    ['091.Mockingbird', '150.Sage_Thrasher'],
                    ['093.Clark_Nutcracker'],
                    ['094.White_breasted_Nuthatch'],
                    ['095.Baltimore_Oriole', '096.Hooded_Oriole', '097.Orchard_Oriole', '098.Scott_Oriole'],
                    ['099.Ovenbird'],
                    ['100.Brown_Pelican', '101.White_Pelican'],
                    ['104.American_Pipit'],
                    ['109.American_Redstart', '158.Bay_breasted_Warbler', '160.Black_throated_Blue_Warbler', '162.Canada_Warbler', '163.Cape_May_Warbler', '164.Cerulean_Warbler', '165.Chestnut_sided_Warbler', '167.Hooded_Warbler', '169.Magnolia_Warbler', '174.Palm_Warbler', '175.Pine_Warbler', '176.Prairie_Warbler', '180.Wilson_Warbler'],
                    ['111.Loggerhead_Shrike', '112.Great_Grey_Shrike'],
                    ['113.Baird_Sparrow', '123.Henslow_Sparrow', '125.Lincoln_Sparrow', '127.Savannah_Sparrow', '129.Song_Sparrow'],
                    ['114.Black_throated_Sparrow', '115.Brewer_Sparrow', '116.Chipping_Sparrow', '117.Clay_colored_Sparrow', '119.Field_Sparrow'],
                    ['118.House_Sparrow'],
                    ['120.Fox_Sparrow', '130.Tree_Sparrow'],
                    ['121.Grasshopper_Sparrow'],
                    ['124.Le_Conte_Sparrow', '126.Nelson_Sharp_tailed_Sparrow', '128.Seaside_Sparrow', '131.Vesper_Sparrow'],
                    ['136.Barn_Swallow', '137.Cliff_Swallow'],
                    ['138.Tree_Swallow'],
                    ['139.Scarlet_Tanager', '140.Summer_Tanager'],
                    ['141.Artic_Tern', '142.Black_Tern', '144.Common_Tern', '145.Elegant_Tern', '146.Forsters_Tern'],
                    ['143.Caspian_Tern'],
                    ['147.Least_Tern'],
                    ['149.Brown_Thrasher'],
                    ['151.Black_capped_Vireo', '152.Blue_headed_Vireo', '156.White_eyed_Vireo', '157.Yellow_throated_Vireo'],
                    ['153.Philadelphia_Vireo', '154.Red_eyed_Vireo', '155.Warbling_Vireo'],
                    ['159.Black_and_white_Warbler', '183.Northern_Waterthrush', '184.Louisiana_Waterthrush'],
                    ['161.Blue_winged_Warbler', '166.Golden_winged_Warbler', '172.Nashville_Warbler', '173.Orange_crowned_Warbler', '179.Tennessee_Warbler'],
                    ['168.Kentucky_Warbler', '170.Mourning_Warbler', '200.Common_Yellowthroat'],
                    ['177.Prothonotary_Warbler', '178.Swainson_Warbler'],
                    ['181.Worm_eating_Warbler', '182.Yellow_Warbler'],
                    ['185.Bohemian_Waxwing', '186.Cedar_Waxwing'],
                    ['187.American_Three_toed_Woodpecker'],
                    ['189.Red_bellied_Woodpecker', '191.Red_headed_Woodpecker'],
                    ['190.Red_cockaded_Woodpecker', '192.Downy_Woodpecker'],
                    ['193.Bewick_Wren', '195.Carolina_Wren'],
                    ['194.Cactus_Wren'],
                    ['196.House_Wren', '199.Winter_Wren'],
                    ['197.Marsh_Wren'],
                    ['198.Rock_Wren']]

level1_mapping = [ #37
                    ['001.Black_footed_Albatross', '002.Laysan_Albatross', '003.Sooty_Albatross'],
                    ['004.Groove_billed_Ani'],
                    ['005.Crested_Auklet', '006.Least_Auklet', '007.Parakeet_Auklet', '008.Rhinoceros_Auklet', '058.Pigeon_Guillemot', '071.Long_tailed_Jaeger', '072.Pomarine_Jaeger', '106.Horned_Puffin'],
                    ['009.Brewer_Blackbird', '010.Red_winged_Blackbird', '011.Rusty_Blackbird', '012.Yellow_headed_Blackbird', '013.Bobolink', '020.Yellow_breasted_Chat', '021.Eastern_Towhee', '026.Bronzed_Cowbird', '027.Shiny_Cowbird', '049.Boat_tailed_Grackle', '076.Dark_eyed_Junco', '088.Western_Meadowlark', '095.Baltimore_Oriole', '096.Hooded_Oriole', '097.Orchard_Oriole', '098.Scott_Oriole', '099.Ovenbird', '109.American_Redstart', '113.Baird_Sparrow', '114.Black_throated_Sparrow', '115.Brewer_Sparrow', '116.Chipping_Sparrow', '117.Clay_colored_Sparrow', '119.Field_Sparrow', '120.Fox_Sparrow', '121.Grasshopper_Sparrow', '122.Harris_Sparrow', '123.Henslow_Sparrow', '124.Le_Conte_Sparrow', '125.Lincoln_Sparrow', '126.Nelson_Sharp_tailed_Sparrow', '127.Savannah_Sparrow', '128.Seaside_Sparrow', '129.Song_Sparrow', '130.Tree_Sparrow', '131.Vesper_Sparrow', '132.White_crowned_Sparrow', '133.White_throated_Sparrow', '148.Green_tailed_Towhee', '158.Bay_breasted_Warbler', '159.Black_and_white_Warbler', '160.Black_throated_Blue_Warbler', '161.Blue_winged_Warbler', '162.Canada_Warbler', '163.Cape_May_Warbler', '164.Cerulean_Warbler', '165.Chestnut_sided_Warbler', '166.Golden_winged_Warbler', '167.Hooded_Warbler', '168.Kentucky_Warbler', '169.Magnolia_Warbler', '170.Mourning_Warbler', '172.Nashville_Warbler', '173.Orange_crowned_Warbler', '174.Palm_Warbler', '175.Pine_Warbler', '176.Prairie_Warbler', '177.Prothonotary_Warbler', '178.Swainson_Warbler', '179.Tennessee_Warbler', '180.Wilson_Warbler', '181.Worm_eating_Warbler', '183.Northern_Waterthrush', '184.Louisiana_Waterthrush', '200.Common_Yellowthroat'],
                    ['014.Indigo_Bunting', '015.Lazuli_Bunting', '016.Painted_Bunting', '017.Cardinal', '054.Blue_Grosbeak', '139.Scarlet_Tanager', '140.Summer_Tanager', '182.Yellow_Warbler'],
                    ['018.Spotted_Catbird'],
                    ['019.Gray_Catbird', '091.Mockingbird', '149.Brown_Thrasher', '150.Sage_Thrasher'],
                    ['023.Brandt_Cormorant', '024.Red_faced_Cormorant', '025.Pelagic_Cormorant', '100.Brown_Pelican', '101.White_Pelican'],
                    ['028.Brown_Creeper'],
                    ['029.American_Crow', '030.Fish_Crow', '073.Blue_Jay', '074.Florida_Jay', '093.Clark_Nutcracker', '107.Common_Raven', '108.White_necked_Raven'],
                    ['031.Black_billed_Cuckoo', '032.Mangrove_Cuckoo', '033.Yellow_billed_Cuckoo'],
                    ['034.Gray_crowned_Rosy_Finch', '035.Purple_Finch', '047.American_Goldfinch', '048.European_Goldfinch'],
                    ['036.Northern_Flicker', '187.American_Three_toed_Woodpecker', '188.Pileated_Woodpecker', '189.Red_bellied_Woodpecker', '190.Red_cockaded_Woodpecker', '191.Red_headed_Woodpecker', '192.Downy_Woodpecker'],
                    ['037.Acadian_Flycatcher', '038.Great_Crested_Flycatcher', '039.Least_Flycatcher', '040.Olive_sided_Flycatcher', '041.Scissor_tailed_Flycatcher', '042.Vermilion_Flycatcher', '043.Yellow_bellied_Flycatcher', '077.Tropical_Kingbird', '078.Gray_Kingbird', '102.Western_Wood_Pewee'],
                    ['045.Northern_Fulmar'],
                    ['046.Gadwall', '087.Mallard', '089.Hooded_Merganser', '090.Red_breasted_Merganser'],
                    ['050.Eared_Grebe', '051.Horned_Grebe'],
                    ['052.Pied_billed_Grebe'],
                    ['053.Western_Grebe'],
                    ['055.Evening_Grosbeak'],
                    ['056.Pine_Grosbeak'],
                    ['057.Rose_breasted_Grosbeak'],
                    ['059.California_Gull', '060.Glaucous_winged_Gull', '061.Heermann_Gull', '062.Herring_Gull', '063.Ivory_Gull', '064.Ring_billed_Gull', '065.Slaty_backed_Gull', '066.Western_Gull', '084.Red_legged_Kittiwake', '141.Artic_Tern', '142.Black_Tern', '143.Caspian_Tern', '144.Common_Tern', '145.Elegant_Tern', '146.Forsters_Tern', '147.Least_Tern'],
                    ['067.Anna_Hummingbird', '068.Ruby_throated_Hummingbird', '069.Rufous_Hummingbird', '070.Green_Violetear'],
                    ['079.Belted_Kingfisher', '082.Ringed_Kingfisher'],
                    ['080.Green_Kingfisher', '081.Pied_Kingfisher'],
                    ['083.White_breasted_Kingfisher'],
                    ['085.Horned_Lark'],
                    ['086.Pacific_Loon'],
                    ['094.White_breasted_Nuthatch'],
                    ['104.American_Pipit'],
                    ['111.Loggerhead_Shrike', '112.Great_Grey_Shrike'],
                    ['118.House_Sparrow'],
                    ['136.Barn_Swallow', '137.Cliff_Swallow', '138.Tree_Swallow'],
                    ['151.Black_capped_Vireo', '152.Blue_headed_Vireo', '153.Philadelphia_Vireo', '154.Red_eyed_Vireo', '155.Warbling_Vireo', '156.White_eyed_Vireo', '157.Yellow_throated_Vireo'],
                    ['185.Bohemian_Waxwing', '186.Cedar_Waxwing'],
                    ['193.Bewick_Wren', '194.Cactus_Wren', '195.Carolina_Wren', '196.House_Wren', '197.Marsh_Wren', '198.Rock_Wren', '199.Winter_Wren']]

level0_mapping = [ #16
                    ['001.Black_footed_Albatross', '002.Laysan_Albatross', '003.Sooty_Albatross', '045.Northern_Fulmar'],
                    ['004.Groove_billed_Ani', '031.Black_billed_Cuckoo', '032.Mangrove_Cuckoo', '033.Yellow_billed_Cuckoo'],
                    ['005.Crested_Auklet', '006.Least_Auklet', '007.Parakeet_Auklet', '008.Rhinoceros_Auklet', '058.Pigeon_Guillemot', '059.California_Gull', '060.Glaucous_winged_Gull', '061.Heermann_Gull', '062.Herring_Gull', '063.Ivory_Gull', '064.Ring_billed_Gull', '065.Slaty_backed_Gull', '066.Western_Gull', '071.Long_tailed_Jaeger', '072.Pomarine_Jaeger', '084.Red_legged_Kittiwake', '106.Horned_Puffin', '141.Artic_Tern', '142.Black_Tern', '143.Caspian_Tern', '144.Common_Tern', '145.Elegant_Tern', '146.Forsters_Tern', '147.Least_Tern'],
                    ['009.Brewer_Blackbird', '010.Red_winged_Blackbird', '011.Rusty_Blackbird', '012.Yellow_headed_Blackbird', '013.Bobolink', '014.Indigo_Bunting', '015.Lazuli_Bunting', '016.Painted_Bunting', '017.Cardinal', '020.Yellow_breasted_Chat', '021.Eastern_Towhee', '026.Bronzed_Cowbird', '027.Shiny_Cowbird', '034.Gray_crowned_Rosy_Finch', '035.Purple_Finch', '047.American_Goldfinch', '048.European_Goldfinch', '049.Boat_tailed_Grackle', '054.Blue_Grosbeak', '055.Evening_Grosbeak', '056.Pine_Grosbeak', '057.Rose_breasted_Grosbeak', '076.Dark_eyed_Junco', '088.Western_Meadowlark', '095.Baltimore_Oriole', '096.Hooded_Oriole', '097.Orchard_Oriole', '098.Scott_Oriole', '099.Ovenbird', '104.American_Pipit', '109.American_Redstart', '113.Baird_Sparrow', '114.Black_throated_Sparrow', '115.Brewer_Sparrow', '116.Chipping_Sparrow', '117.Clay_colored_Sparrow', '118.House_Sparrow', '119.Field_Sparrow', '120.Fox_Sparrow', '121.Grasshopper_Sparrow', '122.Harris_Sparrow', '123.Henslow_Sparrow', '124.Le_Conte_Sparrow', '125.Lincoln_Sparrow', '126.Nelson_Sharp_tailed_Sparrow', '127.Savannah_Sparrow', '128.Seaside_Sparrow', '129.Song_Sparrow', '130.Tree_Sparrow', '131.Vesper_Sparrow', '132.White_crowned_Sparrow', '133.White_throated_Sparrow', '139.Scarlet_Tanager', '140.Summer_Tanager', '148.Green_tailed_Towhee', '158.Bay_breasted_Warbler', '159.Black_and_white_Warbler', '160.Black_throated_Blue_Warbler', '161.Blue_winged_Warbler', '162.Canada_Warbler', '163.Cape_May_Warbler', '164.Cerulean_Warbler', '165.Chestnut_sided_Warbler', '166.Golden_winged_Warbler', '167.Hooded_Warbler', '168.Kentucky_Warbler', '169.Magnolia_Warbler', '170.Mourning_Warbler', '172.Nashville_Warbler', '173.Orange_crowned_Warbler', '174.Palm_Warbler', '175.Pine_Warbler', '176.Prairie_Warbler', '177.Prothonotary_Warbler', '178.Swainson_Warbler', '179.Tennessee_Warbler', '180.Wilson_Warbler', '181.Worm_eating_Warbler', '182.Yellow_Warbler', '183.Northern_Waterthrush', '184.Louisiana_Waterthrush', '200.Common_Yellowthroat'],
                    ['018.Spotted_Catbird'],
                    ['019.Gray_Catbird', '028.Brown_Creeper', '091.Mockingbird', '094.White_breasted_Nuthatch', '149.Brown_Thrasher', '150.Sage_Thrasher', '193.Bewick_Wren', '194.Cactus_Wren', '195.Carolina_Wren', '196.House_Wren', '197.Marsh_Wren', '198.Rock_Wren', '199.Winter_Wren'],
                    ['023.Brandt_Cormorant', '024.Red_faced_Cormorant', '025.Pelagic_Cormorant', '100.Brown_Pelican', '101.White_Pelican'],
                    ['029.American_Crow', '030.Fish_Crow', '073.Blue_Jay', '074.Florida_Jay', '093.Clark_Nutcracker', '107.Common_Raven', '108.White_necked_Raven', '111.Loggerhead_Shrike', '112.Great_Grey_Shrike', '151.Black_capped_Vireo', '152.Blue_headed_Vireo', '153.Philadelphia_Vireo', '154.Red_eyed_Vireo', '155.Warbling_Vireo', '156.White_eyed_Vireo', '157.Yellow_throated_Vireo'],
                    ['036.Northern_Flicker', '079.Belted_Kingfisher', '080.Green_Kingfisher', '081.Pied_Kingfisher', '082.Ringed_Kingfisher', '083.White_breasted_Kingfisher', '187.American_Three_toed_Woodpecker', '188.Pileated_Woodpecker', '189.Red_bellied_Woodpecker', '190.Red_cockaded_Woodpecker', '191.Red_headed_Woodpecker', '192.Downy_Woodpecker'],
                    ['037.Acadian_Flycatcher', '038.Great_Crested_Flycatcher', '039.Least_Flycatcher', '040.Olive_sided_Flycatcher', '041.Scissor_tailed_Flycatcher', '042.Vermilion_Flycatcher', '043.Yellow_bellied_Flycatcher', '077.Tropical_Kingbird', '078.Gray_Kingbird', '102.Western_Wood_Pewee'],
                    ['046.Gadwall', '087.Mallard', '089.Hooded_Merganser', '090.Red_breasted_Merganser'],
                    ['050.Eared_Grebe', '051.Horned_Grebe', '052.Pied_billed_Grebe', '053.Western_Grebe'],
                    ['067.Anna_Hummingbird', '068.Ruby_throated_Hummingbird', '069.Rufous_Hummingbird', '070.Green_Violetear'],
                    ['085.Horned_Lark', '136.Barn_Swallow', '137.Cliff_Swallow', '138.Tree_Swallow'],
                    ['086.Pacific_Loon'],
                    ['185.Bohemian_Waxwing', '186.Cedar_Waxwing']]



all_species = sorted([x for y in level0_mapping for x in y])
species_to_idx = {all_species[i]:i for i in range(len(all_species))}

species_to_ances_level0 = {}
for i in range(len(level0_mapping)):
    for species in level0_mapping[i]:
        species_to_ances_level0[species_to_idx[species]] = i

species_to_ances_level1 = {}
for i in range(len(level1_mapping)):
    for species in level1_mapping[i]:
        species_to_ances_level1[species_to_idx[species]] = i

species_to_ances_level2 = {}
for i in range(len(level2_mapping)):
    for species in level2_mapping[i]:
        species_to_ances_level2[species_to_idx[species]] = i